language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_deploy:
  - ./scripts/rename-binary

deploy:
  provider: releases
  api_key:
    secure: cCMdOW+2UcbGGEHZRVupZo8ikx4lU1R1Xiif40ubXrAXlCHVN9YStCO+rWeHRbIvbDFMRDsKhzzxW907rgBaL5vQ81Xf67XIspIVKoWs85zAjFu5T+LpG9cjKuLU1P5COwsDE/qYAnNBY7CwgYZUdOBcQ88rPvFYtfvmv64lvgZcP8L6rHbb3aqGuGRzLHyEwrtpBqI3Xbtifu0d9AUSBeR+EZnuiG1Z05Z4FhuWhsiet8/RbYvzCl1o96Frla1e+iE6Y11HcEa2tPpjL6zToVCnLTCDh9OujLv+q8mroZpk8y6tUlC3JieYjofiTsaitlWa1behO+8BeypEShedborvPpzPzEGT+AxvyoS588djIaiHVf7ERuxpMSnTgnY9zn4LM1yrNKrr3u8lCvS8tm7x2EgWwxKOFBgASA8iIy6Q/uph/+SVpnZQcKiKT+CUAR1FF75GrcTJTLliTU6iyLMQR2jU48kIMWbe+rVwUHUOnJo57MWaKJQPsoAFiHclRFa//EC5W5stQe5KAJf4JTW4HO0vB//paGzOGYgQdEybtrGYBx3IVXffmBbLPrJu0aPe1UWB2AUu9oLBXlu/n+C0rco2MgRicr68Ilgz7OOeoV6eFqrYeufT8qgGS2KAX4W9uvI1C0ODRftq+SleSDRCQ+vTnwe1QG6obPp/YfE=
  file_glob: true
  file: target/verticareader*
  on:
    repo: joeygibson/verticareader
    tags: true
  skip_cleanup: 'true'
