#!/usr/bin/env bash
set -x

TAG=${GITHUB_REF#refs/*/v}
ARCH=x86_64

if [[ "${OS}" == "macOS-latest" ]]; then
    VENDOR=apple
    OS=darwin
elif [[ "${OS}" == "windows-latest" ]]; then
    VENDOR=microsoft
    OS=windows
    EXT=.exe
else
    VENDOR=unknown
    OS=linux
fi

export TARGET_NAME="${GITHUB_REPOSITORY#joeygibson/}"
echo "PROGRAM_NAME=target/release/${TARGET_NAME}${EXT}" >> $GITHUB_ENV
echo "RELEASE_NAME=${TARGET_NAME}-${TAG}-${ARCH}-${VENDOR}-${OS}${EXT}" >> $GITHUB_ENV
